version: "3.9"

services:

  #-------------------------------#
  #        RoboticSystems         #
  #-------------------------------#

  simulator: 
    container_name: RoboticSystems
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=unix$DISPLAY
    image: ubuntu:20.04
    working_dir: /usr/src/sim
    command:  "bash -c 'apt update && apt upgrade -y && \
              apt install -y g++ python3 python3-pip python3-numpy python3-scipy python3-matplotlib python3-pyqt5 libglu1-mesa-dev freeglut3-dev mesa-common-dev && \
              pip3 install -r requirements.txt && tail -f /dev/null'"
    volumes:
        - $PWD/:/usr/src/sim/
        - $PWD/lib:/usr/src/lib
        - /tmp/.X11-unix:/tmp/.X11-unix
